"""009_Create emailtemplates table

Revision ID: 038c1c2a6886
Revises: 3de7d83b40ad
Create Date: 2024-12-10 18:16:01.378028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038c1c2a6886'
down_revision: Union[str, None] = '3de7d83b40ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
