"""Create emailtemplates table

Revision ID: 3de7d83b40ad
Revises: 814ec76532dd
Create Date: 2024-12-10 18:15:01.630531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3de7d83b40ad'
down_revision: Union[str, None] = '814ec76532dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emailtemplates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=60), nullable=False),
    sa.Column('template_html', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_emailtemplates_id'), 'emailtemplates', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emailtemplates_id'), table_name='emailtemplates')
    op.drop_table('emailtemplates')
    # ### end Alembic commands ###
